[features]
seeds = false
[programs.localnet]
crowd_funding = "98iDNvmZNL18JGNS3BPXZgtkBFCxmQM8QYSQff6q7xzN"
# crowd_funding = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/chung/.config/solana/id.json"
# cluster = "devnet"
# wallet = "./id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
